name: "🐛 バグレポート"
description: バグの新規チケットを作成します。
title: "🐛 [バグ] - <タイトル>"
labels: [
  "bug"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "説明"
      description: 問題の詳細な説明を入力してください
      placeholder: 問題の簡潔で具体的な説明を記入してください...
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "再現手順"
      description: 問題を再現する手順を詳しく説明してください
      value: |
        1. '...'に移動
        2. '....'をクリック
        3. '....'までスクロール
        4. エラーを確認
      render: bash
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "ログ"
      description: 関連するログ出力をコピー＆ペーストしてください。サーバーログとブラウザログの両方を確認してください（該当する場合）。これは自動的にコード形式に整形されるため、バッククォートは不要です。ログを提供できない場合は、N/Aと記入してください。
      render: bash
  - type: textarea
    id: screenshot
    attributes:
      label: "スクリーンショット"
      description: 問題の説明に役立つスクリーンショットがあれば追加してください。
      value: |
        ![説明](リンク.png)
      render: bash
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: "ブラウザ"
      description: どのブラウザで問題が発生していますか？
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: "OS"
      description: 影響を受ける環境は何ですか？
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: false